spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:6001
  sleuth:
    sampler:
      probability: 1
server:
  port: 5001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/,http://localhost:1003/eureka/
  instance:
    status-page-url-path: swagger-ui.html