spring:
  application:
    name: zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/,http://localhost:1003/eureka/
  instance:
    status-page-url-path: zipkin/
server:
  port: 6001
management:
  metrics:
    web:
      server:
        auto-time-requests: false